import { AuthKitProvider } from "@workos-inc/authkit-nextjs/components";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Header from "./components/Header";
import Footer from "./components/Footer";
import { withAuth } from "@workos-inc/authkit-nextjs";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const { user } = await withAuth();
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <AuthKitProvider>
          <main className="container max-w-7xl mx-auto py-4 px-6">
            <Header user={user} />
            {children}
            <Footer />
          </main>
        </AuthKitProvider>
      </body>
    </html>
  );
}
